# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20170123_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=256, verbose_name='\u041d\u0430\u0437\u0432\u0430 \u0413\u0420\u0423\u041f\u0418'),
        ),
    ]
