# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-23 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20170123_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_group',
        ),
    ]
