# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-27 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_ekzamyn'),
    ]

    operations = [
        migrations.AddField(
            model_name='ekzamyn',
            name='ekz_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Group', verbose_name='\u0415\u043a\u0437\u0430\u043c\u0435\u043d\u0430\u0446\u0456\u0439\u043d\u0430 \u0433\u0440\u0443\u043f\u0430'),
        ),
        migrations.AddField(
            model_name='ekzamyn',
            name='inspector',
            field=models.OneToOneField(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.SET_NULL, to='students.Student', verbose_name='\u0406\u043d\u0441\u043f\u0435\u043a\u0442\u043e\u0440'),
        ),
        migrations.AlterField(
            model_name='ekzamyn',
            name='ekzamyn_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u0414\u0430\u0442\u0430 \u0456 \u0447\u0430\u0441 \u043f\u0440\u043e\u0432\u0435\u0434\u0435\u043d\u043d\u044f'),
        ),
    ]
